############# English navigation ##############

# main menu
[[main]]
name = "Accueil"
url = "/"
weight = 1

[[main]]
name = "Qui sommes-nous ?"
url = "/authors"
weight = 2

[[main]]
name = "La liste"
url = "/la-liste"
weight = 3

[[main]]
name = "Nos propositions"
url = "/nos-propositions"
weight = 3

[[main]]
name = "Rencontres"
url = "/rencontres"
weight = 4

[[main]]
name = "Enquête BIATSS"
url = "/enquete"
weight = 5



